networks:
  network-druss:
    driver: bridge

services:
  api:
    image: estacioqueiroz/api-druss:1.2
    container_name: api-druss
    ports:
      - "3006:3006"
    networks:
      - network-druss

  web:
    image: estacioqueiroz/front-druss:1.1
    ports:
      - "5002:5002"
    depends_on:
      - api
    networks:
      - network-druss

