const documents = [
  {
    images: [
      'https://github.com/estacioFilho/imagesProjects/blob/main/druss/produtct/Hair_Reconstructor_The_bottle_is_cylin_3.jpg?raw=true',
    ],
    category: 'treatments',
    name: 'Uso Diário 280ml',
    reviews: 11,
    price: 119.99,
    discount: 0.25,
    description: 'Essential treatment for hair repair. Suitable for all hair types.',
    stock: 43,
  },
  {
    images: [
      'https://github.com/estacioFilho/imagesProjects/blob/main/druss/produtct/hydration_hair_mask_images_with_the_Dr_3.jpg?raw=true',
    ],
    category: 'kits',
    name: 'Kit Mascaras nutrição Liq&Creme 30ml 200g',
    reviews: 7,
    price: 229.99,
    discount: 0.12,
    description: 'Intensive hair mask for deep conditioning. Ideal for damaged hair.',
    stock: 23,
  },
  {
    images: [
      'https://github.com/estacioFilho/imagesProjects/blob/main/druss/produtct/shampoo_bottle_The_bottle_is_cylind_1.jpg?raw=true',
    ],
    category: 'care',
    name: 'Shampoo Uso Diário 300ml',
    reviews: 2,
    price: 139.99,
    discount: 0.27,
    description: 'High-quality shampoo that nourishes and revitalizes hair. Ideal for daily use.',
    stock: 20,
  },
  {
    images: [
      'https://github.com/estacioFilho/imagesProjects/blob/main/druss/produtct/shampoo_druss.jpeg?raw=true',
    ],
    category: 'care',
    name: 'Shampoo Origens 300ml',
    reviews: 2,
    price: 89.99,
    discount: 0.05,
    description: 'High-quality shampoo that nourishes and revitalizes hair. Ideal for daily use.',
    stock: 20,
  },
  {
    images: [
      'https://github.com/estacioFilho/imagesProjects/blob/main/druss/produtct/condicionador_druss.jpeg?raw=true',
    ],
    category: 'care',
    name: 'Condicionador Origens 300ml',
    reviews: 3,
    price: 89.99,
    discount: 0,
    description: 'Conditioner for smooth and manageable hair. Perfect for all hair types.',
    stock: 23,
  },
  {
    images: [
      'https://github.com/estacioFilho/imagesProjects/blob/main/druss/produtct/hydration_hair_mask_2.jpg?raw=true',
    ],
    category: 'treatments',
    name: 'Refil Hidro Mask 50g',
    reviews: 5,
    price: 49.99,
    discount: 0,
    description: 'Intensive hair mask for deep conditioning. Ideal for damaged hair.',
    stock: 55,
  },
  {
    images: [
      'https://github.com/estacioFilho/imagesProjects/blob/main/druss/produtct/nourishing_hair_masks_with_1.jpg?raw=true',
    ],
    category: 'treatments',
    name: 'Mascara de nutrição 258g',
    reviews: 7,
    price: 189.99,
    discount: 0,
    description: 'Intensive hair mask for deep conditioning. Ideal for damaged hair.',
    stock: 23,
  },
  {
    images: [
      'https://github.com/estacioFilho/imagesProjects/blob/main/druss/produtct/hair_mask.jpeg?raw=true',
    ],
    category: 'treatments',
    name: 'Mascara Ocean Blue 2180g',
    reviews: 7,
    price: 129.99,
    discount: 0.03,
    description: 'Intensive hair mask for deep conditioning. Ideal for damaged hair.',
    stock: 23,
  },
  {
    images: [
      'https://github.com/estacioFilho/imagesProjects/blob/main/druss/produtct/brillante_Oil_The_bottle_is_cy_2.jpg?raw=true',
    ],
    category: 'finishers',
    name: 'Brillante Oil 60ml',
    reviews: 5,
    price: 139.99,
    discount: 0,
    description: 'Lightweight oil for shine and softness. Perfect for all hair types.',
    stock: 65,
  },
  {
    images: [
      'https://github.com/estacioFilho/imagesProjects/blob/main/druss/produtct/Druss_brillante_Oil_The_bottle_is_cy_0.jpg?raw=true',
    ],
    category: 'finishers',
    name: 'Brillante Oil dia&noite 60ml',
    reviews: 5,
    price: 187.99,
    discount: 0,
    description: 'Lightweight oil for shine and softness. Perfect for all hair types.',
    stock: 65,
  },
  {
    images: [
      'https://github.com/estacioFilho/imagesProjects/blob/main/druss/produtct/brillante_Oil_The_bottle_is_cy_3.jpg?raw=true',
    ],
    category: 'kits',
    name: 'Kit Brillante Oil 60ml 100g',
    reviews: 18,
    price: 289.97,
    discount: 0.08,
    description: 'Complete kit for frizz control and smooth hair. Ideal for all hair types.',
    stock: 20,
  },
  {
    images: [
      'https://github.com/estacioFilho/imagesProjects/blob/main/druss/produtct/Druss_Professional_Fast_Fix_3.jpg?raw=true',
    ],
    category: 'finishers',
    name: 'Fast Fix 300ml',
    reviews: 6,
    price: 119.99,
    discount: 0,
    description: 'Spray for shine and hold. Ideal for styling and finishing.',
    stock: 20,
  },
];
